# Here lie dragons!
#
# Note that there is no artifact step in this script. We do not want Paperclip
# jars to be built for every push & PR; our CI handles pushes to branches, while
# PRs can themselves link to Paperclip jars if it is necessary. Official such
# PRs will make use of testing builds.

name: Build Paper
on: [push, pull_request]

jobs:
    build:
        # Only run on PRs if the source branch is on a different repo. We do not need run everything twice.
        if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [16, 8]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2
            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@v1
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v2
              with:
                  java-version: ${{ matrix.java }}
                  distribution: 'adopt'
            - name: Cache
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.m2/repository/
                      work/Minecraft
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-paper-3-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: ${{ runner.os }}-paper-3
            - name: Patch and build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./paper build
